from flask import Blueprint, request, jsonify, send_file
from flask_jwt_extended import jwt_required, get_jwt_identity
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import requests
import os
import io
import json
from datetime import datetime
from db import get_connection
from PIL import Image as PILImage, ImageDraw, ImageFont, ImageOps
import io as io_module


reports_bp = Blueprint('reports', __name__)

# Register a Unicode font that supports ₹ (Indian Rupee symbol)
FONT_REGULAR = 'Helvetica'
FONT_BOLD = 'Helvetica-Bold'
try:
    font_dir = os.path.join(os.path.dirname(__file__), '..', 'fonts')
    pdfmetrics.registerFont(TTFont('DejaVuSans', os.path.join(font_dir, 'DejaVuSans.ttf')))
    pdfmetrics.registerFont(TTFont('DejaVuSans-Bold', os.path.join(font_dir, 'DejaVuSans-Bold.ttf')))
    FONT_REGULAR = 'DejaVuSans'
    FONT_BOLD = 'DejaVuSans-Bold'
except Exception as e:
    print(f"⚠️ Could not load DejaVu fonts, falling back to Helvetica (₹ symbol won't render): {e}")

# --- Page geometry: tight margins so content fills the page instead of floating in whitespace ---
PAGE_W, PAGE_H = A4
MARGIN_LR = 1.1 * cm
MARGIN_TOP = 1.0 * cm
MARGIN_BOTTOM = 1.4 * cm  # leaves just enough room for the footer/page number
CONTENT_W = PAGE_W - (2 * MARGIN_LR)  # ~18.8cm usable width

PRIMARY_BLUE = colors.HexColor('#1e3a5f')
ACCENT_RED = colors.HexColor('#c0392b')
LIGHT_GRAY = colors.HexColor('#f8f9fa')
DARK_GRAY = colors.HexColor('#343a40')
BORDER_GRAY = colors.HexColor('#dee2e6')
BAND_BLUE = colors.HexColor('#eaf1f8')


def _page_decorations(canvas, doc, company_name):
    """Footer drawn on every page: company name (left) + page number (right) + a top hairline rule."""
    canvas.saveState()
    canvas.setStrokeColor(BORDER_GRAY)
    canvas.setLineWidth(0.6)
    canvas.line(MARGIN_LR, MARGIN_BOTTOM - 0.35 * cm, PAGE_W - MARGIN_LR, MARGIN_BOTTOM - 0.35 * cm)

    canvas.setFont(FONT_REGULAR, 7.5)
    canvas.setFillColor(colors.gray)
    canvas.drawString(MARGIN_LR, MARGIN_BOTTOM - 0.65 * cm,
                       f"{company_name} — Confidential Report | Auto-generated by Fair Management System")
    canvas.drawRightString(PAGE_W - MARGIN_LR, MARGIN_BOTTOM - 0.65 * cm, f"Page {doc.page}")
    canvas.restoreState()


def generate_pdf_report(field_work, expenses):
    buffer = io.BytesIO()
    company_name = os.getenv('COMPANY_NAME', 'Venus Security')

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=MARGIN_LR, leftMargin=MARGIN_LR,
        topMargin=MARGIN_TOP, bottomMargin=MARGIN_BOTTOM,
        title="Field Work Expense Report",
    )

    story = []

    # ----------------------------------------------------------------
    # Letterhead banner — full content width, no dead margin above it
    # ----------------------------------------------------------------
    banner_title_style = ParagraphStyle('btitle', fontName=FONT_BOLD, fontSize=19, textColor=colors.white,
                                         leading=22, spaceAfter=2)
    banner_sub_style = ParagraphStyle('bsub', fontName=FONT_REGULAR, fontSize=10.5,
                                       textColor=colors.HexColor('#cfe0f0'), leading=13)
    banner_meta_style = ParagraphStyle('bmeta', fontName=FONT_REGULAR, fontSize=8.5,
                                        textColor=colors.HexColor('#cfe0f0'), alignment=TA_RIGHT, leading=12)
    banner_status_style = ParagraphStyle('bstatus', fontName=FONT_BOLD, fontSize=11,
                                          textColor=colors.white, alignment=TA_RIGHT, leading=14)

    logo_path = os.path.join(os.path.dirname(__file__), '..', '..', 'frontend', 'public', 'logo.jpeg')
    logo_cell = ''
    logo_w = 0
    if os.path.exists(logo_path):
        try:
            logo_cell = RLImage(logo_path, width=1.5 * cm, height=1.5 * cm)
            logo_w = 2.0 * cm
        except Exception:
            logo_cell = ''
            logo_w = 0

    title_block = [
        Paragraph(company_name, banner_title_style),
        Paragraph("Field Work Expense Report", banner_sub_style),
    ]

    status_text = (field_work.get('status', '') or '').upper() or 'N/A'
    meta_block = [
        Paragraph(status_text, banner_status_style),
        Spacer(1, 2),
        Paragraph(f"Generated: {datetime.now().strftime('%d %b %Y, %I:%M %p')}", banner_meta_style),
    ]

    if logo_w:
        banner_cols = [logo_w, CONTENT_W - logo_w - 5.8 * cm, 5.8 * cm]
        banner_row = [logo_cell, title_block, meta_block]
    else:
        banner_cols = [CONTENT_W - 5.8 * cm, 5.8 * cm]
        banner_row = [title_block, meta_block]

    banner_table = Table([banner_row], colWidths=banner_cols)
    banner_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), PRIMARY_BLUE),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (0, 0), 'CENTER'),
        ('LEFTPADDING', (0, 0), (0, 0), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (-1, 0), (-1, 0), 10),
    ]))
    story.append(banner_table)
    story.append(Spacer(1, 0.35 * cm))

    # ----------------------------------------------------------------
    # Field work details — compact two-column info grid, full width
    # ----------------------------------------------------------------
    detail_style = ParagraphStyle('detail', fontName=FONT_REGULAR, fontSize=9.5, textColor=DARK_GRAY,
                                   leading=13)
    label_style = ParagraphStyle('label', fontName=FONT_BOLD, fontSize=9, textColor=PRIMARY_BLUE, leading=12)

    info_rows = [
        ('Field Work Title', field_work.get('title', '') or '-'),
        ('Employee Name', field_work.get('employee_name', '') or '-'),
        ('Location', field_work.get('location', '') or 'N/A'),
        ('Admin', field_work.get('admin_name', '') or '-'),
        ('Start Date', str(field_work.get('started_at', '')) or '-'),
        ('End Date', str(field_work.get('completed_at', '')) or 'In Progress'),
    ]

    # Two label/value pairs per row so the grid uses the full page width
    info_data = []
    for i in range(0, len(info_rows), 2):
        left = info_rows[i]
        right = info_rows[i + 1] if i + 1 < len(info_rows) else ('', '')
        info_data.append([
            Paragraph(left[0], label_style), Paragraph(left[1], detail_style),
            Paragraph(right[0], label_style), Paragraph(right[1], detail_style),
        ])

    col_a = 3.2 * cm
    col_b = (CONTENT_W / 2) - col_a
    info_table = Table(info_data, colWidths=[col_a, col_b, col_a, col_b])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), LIGHT_GRAY),
        ('BACKGROUND', (2, 0), (2, -1), LIGHT_GRAY),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_GRAY),
        ('LEFTPADDING', (0, 0), (-1, -1), 7),
        ('RIGHTPADDING', (0, 0), (-1, -1), 7),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 0.4 * cm))

    # ----------------------------------------------------------------
    # Expense table — sized to fill the full content width
    # ----------------------------------------------------------------
    story.append(Paragraph("Expense Details", ParagraphStyle('eh', fontName=FONT_BOLD, fontSize=12.5,
                            textColor=PRIMARY_BLUE, spaceAfter=6)))

    remark_style = ParagraphStyle('remark', fontName=FONT_REGULAR, fontSize=9, textColor=DARK_GRAY, leading=12)
    cell_style = ParagraphStyle('cell', fontName=FONT_REGULAR, fontSize=9, textColor=DARK_GRAY,
                                 alignment=TA_CENTER, leading=12)
    amount_style = ParagraphStyle('amt', fontName=FONT_BOLD, fontSize=9.5, textColor=ACCENT_RED,
                                   alignment=TA_CENTER, leading=12)
    header_style_cell = ParagraphStyle('hc', fontName=FONT_BOLD, fontSize=9.5, textColor=colors.white,
                                        alignment=TA_CENTER)

    headers = ['#', 'Date & Time', 'Amount', 'Remark', 'Screenshot']
    table_data = [[Paragraph(h, header_style_cell) for h in headers]]

    total = 0
    for i, exp in enumerate(expenses, 1):
        amt = float(exp.get('amount', 0))
        total += amt
        date_str = str(exp.get('added_at', ''))[:16]
        remark = exp.get('remark', '') or ''
        has_ss = 'Yes ✓' if exp.get('payment_screenshot_url') else '—'

        table_data.append([
            Paragraph(str(i), cell_style),
            Paragraph(date_str, cell_style),
            Paragraph(f"₹ {amt:,.2f}", amount_style),
            Paragraph(remark, remark_style),
            Paragraph(has_ss, cell_style),
        ])

    table_data.append([
        Paragraph('', cell_style),
        Paragraph('TOTAL', ParagraphStyle('tot', fontName=FONT_BOLD, fontSize=10, textColor=PRIMARY_BLUE,
                                           alignment=TA_CENTER)),
        Paragraph(f"₹ {total:,.2f}", ParagraphStyle('totamt', fontName=FONT_BOLD, fontSize=10.5,
                                                      textColor=PRIMARY_BLUE, alignment=TA_CENTER)),
        Paragraph('', cell_style),
        Paragraph('', cell_style),
    ])

    # Widths scaled to use the full content width (CONTENT_W ≈ 18.8cm)
    exp_col_widths = [1.1 * cm, 3.3 * cm, 3.0 * cm, CONTENT_W - (1.1 + 3.3 + 3.0 + 2.3) * cm, 2.3 * cm]
    exp_table = Table(table_data, colWidths=exp_col_widths, repeatRows=1)
    exp_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), PRIMARY_BLUE),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, LIGHT_GRAY]),
        ('BACKGROUND', (0, -1), (-1, -1), BAND_BLUE),
        ('LINEBELOW', (0, -1), (-1, -1), 1.2, PRIMARY_BLUE),
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_GRAY),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 5),
        ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(exp_table)
    story.append(Spacer(1, 0.5 * cm))

    # ----------------------------------------------------------------
    # Payment Screenshots — clean uniform 3-column matrix
    # Each thumbnail is center-cropped to an identical square so the
    # grid lines up perfectly regardless of the source image's aspect ratio.
    # ----------------------------------------------------------------
    ss_expenses = [e for e in expenses if e.get('payment_screenshot_url')]
    if ss_expenses:
        story.append(Paragraph("Payment Screenshots", ParagraphStyle('ssh', fontName=FONT_BOLD, fontSize=12.5,
                                textColor=PRIMARY_BLUE, spaceAfter=8)))

        caption_style = ParagraphStyle('cap', fontName=FONT_BOLD, fontSize=8.5, textColor=PRIMARY_BLUE,
                                        alignment=TA_CENTER, spaceBefore=4, leading=11)
        sub_caption_style = ParagraphStyle('subcap', fontName=FONT_REGULAR, fontSize=7.5, textColor=colors.gray,
                                            alignment=TA_CENTER, leading=10)

        COLS = 3
        cell_pad = 0.3 * cm
        col_width = CONTENT_W / COLS
        thumb_pt = (col_width - 2 * cell_pad) - 4  # square box size in points, fits inside the cell

        cells = []
        for idx, exp in enumerate(ss_expenses, 1):
            try:
                resp = requests.get(exp['payment_screenshot_url'], timeout=10)
                resp.raise_for_status()
                img_buffer = io.BytesIO(resp.content)
                pil_img = PILImage.open(img_buffer)
                pil_img.load()
                pil_img = pil_img.convert('RGB')

                if pil_img.width < 1 or pil_img.height < 1:
                    raise ValueError(f"Bad image dimensions: {pil_img.width}x{pil_img.height}")

                # Render the crop at 2x for crisp output, then place at thumb_pt size
                target_px = int((thumb_pt / 28.3465) * 96 * 2)  # pt -> inch -> px @192dpi
                square = ImageOps.fit(pil_img, (target_px, target_px), method=PILImage.LANCZOS)

                tmp_buf = io.BytesIO()
                square.save(tmp_buf, format='JPEG', quality=88)
                tmp_buf.seek(0)

                rl_img = RLImage(tmp_buf, width=thumb_pt, height=thumb_pt)
                date_str = str(exp.get('added_at', ''))[:16]
                cell_content = [
                    rl_img,
                    Paragraph(f"#{idx} &nbsp;•&nbsp; ₹ {float(exp['amount']):,.2f}", caption_style),
                    Paragraph(date_str, sub_caption_style),
                ]
            except Exception as img_err:
                print(f"⚠️ Screenshot render failed for expense {exp.get('id')}: {img_err}")
                placeholder = Table([['']], colWidths=[thumb_pt], rowHeights=[thumb_pt])
                placeholder.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, -1), LIGHT_GRAY),
                    ('BOX', (0, 0), (-1, -1), 0.5, BORDER_GRAY),
                ]))
                cell_content = [
                    placeholder,
                    Paragraph(f"#{idx} — Unavailable", caption_style),
                ]
            cells.append(cell_content)

        for i in range(0, len(cells), COLS):
            row_cells = cells[i:i + COLS]
            while len(row_cells) < COLS:
                row_cells.append('')

            row_table = Table([row_cells], colWidths=[col_width] * COLS)
            row_table.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('BOX', (0, 0), (-1, -1), 0.4, BORDER_GRAY),
                ('INNERGRID', (0, 0), (-1, -1), 0.4, BORDER_GRAY),
                ('TOPPADDING', (0, 0), (-1, -1), cell_pad),
                ('BOTTOMPADDING', (0, 0), (-1, -1), cell_pad),
                ('LEFTPADDING', (0, 0), (-1, -1), cell_pad),
                ('RIGHTPADDING', (0, 0), (-1, -1), cell_pad),
            ]))
            story.append(row_table)

        story.append(Spacer(1, 0.45 * cm))

    # ----------------------------------------------------------------
    # Total summary band — full width
    # ----------------------------------------------------------------
    summary_data = [[
        Paragraph('TOTAL EXPENSES', ParagraphStyle('ts', fontName=FONT_BOLD, fontSize=13,
                  textColor=colors.white, alignment=TA_LEFT)),
        Paragraph(f'₹ {total:,.2f}', ParagraphStyle('ta', fontName=FONT_BOLD, fontSize=15,
                  textColor=colors.white, alignment=TA_RIGHT))
    ]]
    summary_table = Table(summary_data, colWidths=[CONTENT_W / 2, CONTENT_W / 2])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), PRIMARY_BLUE),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (0, 0), 12),
        ('RIGHTPADDING', (-1, 0), (-1, 0), 12),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(summary_table)

    doc.build(
        story,
        onFirstPage=lambda c, d: _page_decorations(c, d, company_name),
        onLaterPages=lambda c, d: _page_decorations(c, d, company_name),
    )
    buffer.seek(0)
    return buffer, total

def generate_whatsapp_image(field_work, expenses):
    """Build one composite report image: header + expense list + screenshot thumbnails"""
    width = 800
    padding = 30
    row_height = 50
    thumb_size = 150

    # Calculate height needed
    screenshots = [e for e in expenses if e.get('payment_screenshot_url')]
    thumb_rows = (len(screenshots) + 2) // 3  # 3 thumbnails per row
    header_height = 220
    expense_list_height = len(expenses) * row_height + 60
    thumb_section_height = (thumb_rows * (thumb_size + 50)) + 80 if screenshots else 0
    footer_height = 100
    total_height = header_height + expense_list_height + thumb_section_height + footer_height

    img = PILImage.new('RGB', (width, total_height), color='#ffffff')
    draw = ImageDraw.Draw(img)

    try:
        font_bold_lg = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 26)
        font_bold_md = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 18)
        font_reg = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 15)
        font_sm = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 12)
    except:
        font_bold_lg = font_bold_md = font_reg = font_sm = ImageFont.load_default()

    primary = (30, 58, 95)
    accent = (192, 57, 43)
    gray = (100, 116, 139)
    light_bg = (248, 249, 250)

    # Header band
    draw.rectangle([0, 0, width, header_height], fill=primary)
    company_name = os.getenv('COMPANY_NAME', 'Venus Security')

    # Try to paste logo
    y_cursor = 25
    try:
        logo_path = os.path.join(os.path.dirname(__file__), '..', 'static', 'logo.png')
        if os.path.exists(logo_path):
            logo = PILImage.open(logo_path).convert('RGBA')
            logo.thumbnail((70, 70))
            img.paste(logo, (padding, y_cursor), logo)
            text_x = padding + 85
        else:
            text_x = padding
    except:
        text_x = padding

    draw.text((text_x, y_cursor + 5), company_name, font=font_bold_lg, fill='white')
    draw.text((text_x, y_cursor + 40), "Field Work Expense Report", font=font_reg, fill=(200, 215, 230))

    y_cursor = 110
    draw.text((padding, y_cursor), f"Work: {field_work.get('title','')}", font=font_bold_md, fill='white')
    draw.text((padding, y_cursor + 28), f"Employee: {field_work.get('employee_name','')}  |  Location: {field_work.get('location','N/A')}", font=font_sm, fill=(200, 215, 230))
    draw.text((padding, y_cursor + 50), f"Duration: {str(field_work.get('started_at',''))[:16]} → {str(field_work.get('completed_at','In Progress'))[:16]}", font=font_sm, fill=(200, 215, 230))

    # Expense list
    y = header_height + 25
    draw.text((padding, y), "Expense Details", font=font_bold_md, fill=primary)
    y += 35
    total = 0
    for i, exp in enumerate(expenses):
        amt = float(exp.get('amount', 0))
        total += amt
        row_bg = light_bg if i % 2 == 0 else (255, 255, 255)
        draw.rectangle([padding-10, y-8, width-padding+10, y + row_height - 15], fill=row_bg)
        draw.text((padding, y), f"₹{amt:,.2f}", font=font_bold_md, fill=accent)
        remark = exp.get('remark', '')
        if len(remark) > 55:
            remark = remark[:55] + '...'
        draw.text((padding + 140, y), remark, font=font_reg, fill=(50, 50, 50))
        draw.text((width - padding - 130, y), str(exp.get('added_at',''))[:16], font=font_sm, fill=gray)
        y += row_height

    # Total bar
    y += 10
    draw.rectangle([padding-10, y, width-padding+10, y+50], fill=primary)
    draw.text((padding, y+13), "TOTAL EXPENSES", font=font_bold_md, fill='white')
    draw.text((width-padding-150, y+10), f"₹{total:,.2f}", font=font_bold_lg, fill='white')
    y += 80

    # Screenshot thumbnails grid
    if screenshots:
        draw.text((padding, y), f"Payment Screenshots ({len(screenshots)})", font=font_bold_md, fill=primary)
        y += 35
        x_cursor = padding
        col = 0
        for exp in screenshots:
            try:
                resp = requests.get(exp['payment_screenshot_url'], timeout=10)
                thumb = PILImage.open(io_module.BytesIO(resp.content)).convert('RGB')
                thumb.thumbnail((thumb_size, thumb_size))
                # Center thumbnail in its cell
                cell_x = x_cursor + (thumb_size - thumb.width) // 2
                img.paste(thumb, (cell_x, y))
                draw.rectangle([x_cursor, y, x_cursor + thumb_size, y + thumb_size], outline=(220,220,220), width=2)
                amt_label = f"₹{float(exp.get('amount',0)):,.0f}"
                draw.text((x_cursor, y + thumb_size + 5), amt_label, font=font_sm, fill=primary)
            except Exception:
                draw.rectangle([x_cursor, y, x_cursor + thumb_size, y + thumb_size], fill=(230,230,230))
                draw.text((x_cursor + 30, y + thumb_size//2), "No Image", font=font_sm, fill=gray)

            col += 1
            if col >= 3:
                col = 0
                x_cursor = padding
                y += thumb_size + 50
            else:
                x_cursor += thumb_size + 25

        if col != 0:
            y += thumb_size + 50

    # Footer
    y += 20
    draw.line([padding, y, width-padding, y], fill=(220,220,220), width=1)
    y += 15
    draw.text((padding, y), f"{company_name} — Auto-generated by Fair Management System", font=font_sm, fill=gray)

    buffer = io_module.BytesIO()
    img.save(buffer, format='JPEG', quality=85)
    buffer.seek(0)
    return buffer, total

@reports_bp.route('/generate/<int:fw_id>', methods=['GET'])
@jwt_required()
def generate_report(fw_id):
    identity = json.loads(get_jwt_identity())
    if identity['role'] not in ('master', 'admin'):
        return jsonify({'error': 'Unauthorized'}), 403

    try:
        conn = get_connection()
        with conn.cursor() as cur:
            cur.execute("""
                SELECT fw.*, u.name as employee_name, u.phone as employee_phone,
                       a.name as admin_name
                FROM field_works fw
                JOIN users u ON u.id = fw.employee_id
                JOIN users a ON a.id = fw.admin_id
                WHERE fw.id = %s
            """, (fw_id,))
            field_work = cur.fetchone()
            if not field_work:
                return jsonify({'error': 'Field work not found'}), 404

            cur.execute("""
                SELECT e.*, u.name as employee_name
                FROM expenses e JOIN users u ON u.id = e.employee_id
                WHERE e.field_work_id = %s ORDER BY e.added_at ASC
            """, (fw_id,))
            expenses = cur.fetchall()
        conn.close()

        for key in ('started_at', 'completed_at', 'created_at'):
            if field_work.get(key):
                field_work[key] = str(field_work[key])
        for exp in expenses:
            if exp.get('added_at'):
                exp['added_at'] = str(exp['added_at'])

        pdf_buffer, total = generate_pdf_report(field_work, expenses)
        filename = f"Report_{field_work['title'].replace(' ','_')}_{fw_id}.pdf"
        return send_file(pdf_buffer, mimetype='application/pdf',
                         as_attachment=True, download_name=filename)
    except Exception as e:
        import traceback
        traceback.print_exc()
        return jsonify({'error': str(e)}), 500

@reports_bp.route('/send-whatsapp/<int:fw_id>', methods=['POST'])
@jwt_required()
def send_whatsapp(fw_id):
    identity = json.loads(get_jwt_identity())
    if identity['role'] not in ('master', 'admin'):
        return jsonify({'error': 'Unauthorized'}), 403
    return _send_whatsapp_report(fw_id)


def _send_whatsapp_report(fw_id):
    """Internal: builds composite image, uploads to Cloudinary, sends WhatsApp template"""
    import cloudinary.uploader
    try:
        conn = get_connection()
        with conn.cursor() as cur:
            cur.execute("""
                SELECT fw.*, u.name as employee_name, u.phone as employee_phone,
                       a.name as admin_name
                FROM field_works fw
                JOIN users u ON u.id = fw.employee_id
                JOIN users a ON a.id = fw.admin_id
                WHERE fw.id = %s
            """, (fw_id,))
            field_work = cur.fetchone()
            if not field_work:
                conn.close()
                return jsonify({'error': 'Field work not found'}), 404

            cur.execute("""
                SELECT e.*, u.name as employee_name FROM expenses e
                JOIN users u ON u.id = e.employee_id
                WHERE e.field_work_id = %s ORDER BY e.added_at ASC
            """, (fw_id,))
            expenses = cur.fetchall()
        conn.close()

        for key in ('started_at', 'completed_at', 'created_at'):
            if field_work.get(key):
                field_work[key] = str(field_work[key])
        for exp in expenses:
            if exp.get('added_at'):
                exp['added_at'] = str(exp['added_at'])

        # Build composite report image with all screenshots embedded
        image_buffer, total = generate_whatsapp_image(field_work, expenses)

        # Upload composite image to Cloudinary so WhatsApp can fetch it via public URL
        upload_result = cloudinary.uploader.upload(
            image_buffer,
            folder='fair_management/reports',
            resource_type='image'
        )
        report_image_url = upload_result['secure_url']

        company_name = os.getenv('COMPANY_NAME', 'Venus Security')
        phone_number_id = os.getenv('WHATSAPP_PHONE_NUMBER_ID')
        access_token = os.getenv('WHATSAPP_ACCESS_TOKEN')
        to_number = os.getenv('COMPANY_WHATSAPP_NUMBER')
        template_name = os.getenv('WHATSAPP_TEMPLATE_NAME', 'fair_expense_report')

        if not phone_number_id or not access_token or not to_number:
            return jsonify({'error': 'WhatsApp not configured. Please set env variables.'}), 500

        payload = {
            "messaging_product": "whatsapp",
            "to": to_number,
            "type": "template",
            "template": {
                "name": template_name,
                "language": {"code": "en"},
                "components": [
                    {
                        "type": "header",
                        "parameters": [
                            {"type": "image", "image": {"link": report_image_url}}
                        ]
                    },
                    {
                        "type": "body",
                        "parameters": [
                            {"type": "text", "text": company_name},
                            {"type": "text", "text": field_work.get('title', '')},
                            {"type": "text", "text": field_work.get('employee_name', '')},
                            {"type": "text", "text": field_work.get('location', 'N/A')},
                            {"type": "text", "text": f"₹{total:,.2f}"}
                        ]
                    }
                ]
            }
        }

        response = requests.post(
            f"https://graph.facebook.com/v18.0/{phone_number_id}/messages",
            headers={"Authorization": f"Bearer {access_token}", "Content-Type": "application/json"},
            json=payload
        )

        if response.status_code == 200:
            conn2 = get_connection()
            with conn2.cursor() as cur2:
                cur2.execute("UPDATE field_works SET report_sent = TRUE WHERE id = %s", (fw_id,))
            conn2.close()
            return jsonify({'message': 'WhatsApp report sent successfully', 'image_url': report_image_url})
        else:
            return jsonify({'error': 'WhatsApp send failed', 'details': response.json()}), 500

    except Exception as e:
        return jsonify({'error': str(e)}), 500
    
    
@reports_bp.route('/summary', methods=['GET'])
@jwt_required()
def get_summary():
    identity = json.loads(get_jwt_identity())
    if identity['role'] not in ('master', 'admin'):
        return jsonify({'error': 'Unauthorized'}), 403
    try:
        conn = get_connection()
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) as total FROM field_works")
            total_fw = cur.fetchone()['total']
            cur.execute("SELECT COUNT(*) as active FROM field_works WHERE status='active'")
            active_fw = cur.fetchone()['active']
            cur.execute("SELECT COALESCE(SUM(total_expense),0) as total FROM field_works")
            total_expense = cur.fetchone()['total']
            cur.execute("SELECT COUNT(*) as total FROM users WHERE role='employee'")
            total_employees = cur.fetchone()['total']
            cur.execute("""
                SELECT COUNT(DISTINCT fw.employee_id) as count FROM field_works fw WHERE fw.status='active'
            """)
            on_duty = cur.fetchone()['count']
        conn.close()
        return jsonify({
            'total_field_works': total_fw,
            'active_field_works': active_fw,
            'total_expenses': float(total_expense),
            'total_employees': total_employees,
            'employees_on_duty': on_duty
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500